version: '3.8'

services:
  ems-backend:
    image: us-central1-docker.pkg.dev/prefab-lamp-498812-u8/ems-repo/ems-backend:latest
    container_name: ems-backend
    restart: always
    environment:
      APPLICATION_NAME: ${APPLICATION_NAME:-ems-spanner}
      SPANNER_PROJECT_ID: ${SPANNER_PROJECT_ID}
      SPANNER_INSTANCE_ID: ${SPANNER_INSTANCE_ID}
      SPANNER_DATABASE: ${SPANNER_DATABASE}
      SECRET: ${JWT_SECRET}
      EXPIRATION: ${JWT_EXPIRATION:-86400000}
      PORT: ${BACKEND_PORT:-8080}
      SERVICE_NAME: /${BACKEND_SERVICE_NAME:-employee-service}
      AUTO_DDL: ${AUTO_DDL:-none}
      SHOW_SQL: "${SHOW_SQL:-true}"
      DB_PLATFORM: ${DB_PLATFORM:-org.hibernate.dialect.SpannerDialect}
      DRIVER_CLASS: ${DRIVER_CLASS:-com.google.cloud.spanner.jdbc.JdbcDriver}

  ems-frontend:
    image: us-central1-docker.pkg.dev/prefab-lamp-498812-u8/ems-repo/ems-frontend:latest
    container_name: ems-frontend
    restart: always
    ports:
      - "${FRONTEND_PORT:-80}:80"
    depends_on:
      - ems-backend
